import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { basename, join } from 'node:path'
import { parse } from 'yaml'

const root = process.cwd()
const generatedDir = join(root, 'content/generated')

function readMarkdown(file) {
  const raw = readFileSync(file, 'utf8')
  const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/)

  if (!match) {
    throw new Error(`Missing frontmatter in ${file}`)
  }

  return {
    data: parse(match[1]) || {},
    body: match[2].trim()
  }
}

function writeModule(file, namedExport, value) {
  writeFileSync(
    join(generatedDir, file),
    `// Generated by scripts/generate-content.mjs. Edit Markdown under content/ instead.\nexport const ${namedExport} = ${JSON.stringify(value, null, 2)}\n`
  )
}

function normalizeProjectImage(image) {
  if (!image) return image
  if (/^(?:https?:|data:|blob:|\/)/.test(image)) return image
  if (image.startsWith('public/')) return image.slice('public'.length)
  return `/media/projecten/${image}`
}

function loadSite() {
  const { data } = readMarkdown(join(root, 'content/site.md'))
  return data
}

function loadPages() {
  const dir = join(root, 'content/pages')
  if (!existsSync(dir)) return {}

  return Object.fromEntries(
    readdirSync(dir)
      .filter((file) => file.endsWith('.md'))
      .sort()
      .map((file) => {
        const { data, body } = readMarkdown(join(dir, file))
        const key = data.slug || basename(file, '.md')

        return [key, { ...data, body }]
      })
  )
}

function loadProjects() {
  const dir = join(root, 'content/projects')
  if (!existsSync(dir)) return []

  return readdirSync(dir)
    .filter((file) => file.endsWith('.md'))
    .map((file) => {
      const { data, body } = readMarkdown(join(dir, file))
      const images = (data.images || data.gallery || []).map(normalizeProjectImage)
      const project = {
        ...data,
        slug: data.slug || basename(file, '.md'),
        body,
        cover: data.cover ? normalizeProjectImage(data.cover) : images[0],
        gallery: images,
        materials: data.materials || [],
        appliances: data.appliances || [],
        question: data.question || 'Hoe wordt deze keukenopstelling rustig, bruikbaar en passend bij de woning?',
        challenge: data.challenge || 'De opstelling moest materiaal, bergruimte, looplijnen en dagelijks gebruik in balans brengen.',
        solution: data.solution || 'De bulthaup-systeemopbouw houdt de lijnen rustig en laat materiaal, werkblad en opstelling de ruimte bepalen.'
      }

      delete project.images
      delete project.order

      return { order: data.order || 999, project }
    })
    .sort((a, b) => a.order - b.order || a.project.title.localeCompare(b.project.title, 'nl'))
    .map(({ project }) => project)
}

mkdirSync(generatedDir, { recursive: true })

writeModule('site.mjs', 'site', loadSite())
writeModule('pages.mjs', 'pages', loadPages())
writeModule('projects.mjs', 'projects', loadProjects())

console.log('Generated content modules')
